// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApi.Models.Livro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("autor")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            id = 1,
                            autor = "Antoine de Saint-Exupéry",
                            descricao = "O Pequeno Principe",
                            titulo = "O Pequeno Principe"
                        },
                        new
                        {
                            id = 2,
                            autor = "Miguel de Cervantes",
                            descricao = "Dom Quixote",
                            titulo = "Dom Quixote"
                        },
                        new
                        {
                            id = 3,
                            autor = "Alfredo d'Escragnolle Taunay",
                            descricao = "Inocencia",
                            titulo = "Inocencia"
                        },
                        new
                        {
                            id = 4,
                            autor = "Sun Tzu",
                            descricao = "é um tratado militar escrito durante o século IV a.C",
                            titulo = "A Arte da Guerra"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
